### ISSUE TITLE
new wall touch function

### ISSUE THREAD

**Issue by lukasgehrke** [lukasgehrke/IMT_v2_vizard#1]
implement new wall touch function with following features: circle only has 1 size and does not move with the hand object but stays in place of first collision (make feedback non-interactive); fades out for 100ms starting after 200ms of being visible

**Comment by benjaminpaulisch** [comment]
Two versions to implement for testing:
1) timeout betweeen walltouches (there can't be a second wall touch while the first walltouch is still being visualized and there has to be an additional pause before a new wall touch can be visualized)
2) A new wall touch would remove the old wall touch instantly

**Comment by lukasgehrke** [comment]
create mazes as 3D objects in external 3D sketch software and then make a collidemesh and render them invisible
