### ISSUE TITLE
Rote Scheibe Feedback 90 Grad gedreht

### ISSUE THREAD

**Issue by lukasgehrke** [lukasgehrke/IMT_v2_vizard#13]
Nach weissem feedback (korrekt), springt die scheibe zu rot und dreht um 90 grad

**Comment by benjaminpaulisch** [comment]
Die Orientierung der roten Scheibe war immer gleich, egal welche Orientierung die Wand hatte. Habe die Berechnung der roten Scheibe an die der weißen und blauen angeglichen, denn diese funktionierten korrekt.
