### ISSUE TITLE
add global landmarks

### ISSUE THREAD

**Issue by lukasgehrke** [lukasgehrke/IMT_v2_vizard#8]
a function to place a landmark should allow specifyng a position and size of the landmark. Decide on position for each maze

**Comment by benjaminpaulisch** [comment]
ToDo:
In der Maze Klasse:
Individuelle Position fürs Landmark: 30 Einheiten geradeaus vom Startpunkt (muss in Relation zur Größe passen, so dass sich die Position auch visuell verändert). Skalierung des Landmarks passen sezten.

Klasse Landmark erstellen mit Parametern (Position, Skalierung, globel/local). Erstellung der Landmarks aus VisualMazeScene raus nehmen.
